---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitor.sivasathwik.online
  resources:
  - monitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.sivasathwik.online
  resources:
  - monitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitor.sivasathwik.online
  resources:
  - monitors/status
  verbs:
  - get
  - patch
  - update
