apiVersion: monitor.sivasathwik.online/v1
kind: Monitor
metadata:
  labels:
    app.kubernetes.io/name: k8-ops
    app.kubernetes.io/managed-by: kustomize
  name: monitor-sample
spec:
  # TODO(user): Add fields here
  start: 5
  end: 10
  replicas: 5
  deployments:
    - name: abc
      namespace: default
